AWS_ACCESS_KEY: AKIAIYGBHONRPVFMU3FQ
AWS_SECRET_KEY: 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
VPC_CIDR_BLOCK: 172.31.0.0/16
SUBNET_CIDR_BLOCK: 172.31.80.0/20
LINUX_AMI_ID: ami-059eeca93cf09eebd
KEY_NAME: bgarcia
REGION_NAME: us-east-1
