AWS_ACCESS_KEY: AKIAJ6RGNB6K5GXXGMGQ
AWS_SECRET_KEY: 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
VPC_CIDR_BLOCK: 172.31.0.0/16
SUBNET_CIDR_BLOCK: 172.31.80.0/20
LINUX_AMI_ID: ami-059eeca93cf09eebd
KEY_NAME: bgarcia-home
REGION_NAME: us-east-1
